  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clipboard.Properties 
{
    internal partial class Settings 
    {

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZhYAOg9H/yYYOCYHPZ8Lmwr8GmYmB8A3")]
        public string DropBoxAppKey => ((string)(this["DropBoxAppKey"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N2luQCMxJTj3KWMukaxHgWLSJCGRgiVADzzVY/JCxzRD+o5G12n3TQ==")]
        public string DropBoxRedirectUri => ((string)(this["DropBoxRedirectUri"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fuDuzRMqQHieR17LUty1muooFxZbm2TItkEyEXICCQ9IxOhfzi3yqFjhAY6v3tu/j61/ACfUXrb8nNhgsnxYlyI5gp2HUF0sHAujMG2wQA8=")]
        public string OneDriveClientId => ((string)(this["OneDriveClientId"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N2luQCMxJTj3KWMukaxHgSZcUVBSwdyqb8pKISm7v+Z9U/nanUQLjWCKDH4mKY/RrtiORmwKV6YiODagTYCWWnW1I1uN2T5ulDomvC+y+iz3/X6cQUjprWITCv5VRudR")]
        public string OneDriveRedirectUri => ((string)(this["OneDriveRedirectUri"]));
    }
}
