  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clipboard.Properties 
{
    internal partial class Settings 
    {

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e/1sjAGkdierO9cmC3Tz69sqOrxj2kHv")]
        public string DropBoxAppKey => ((string)(this["DropBoxAppKey"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rp2YO1i8XYXs24egYC3SoFrodumdVibbiqGXOCgHQeBFFANXaad+mA==")]
        public string DropBoxRedirectUri => ((string)(this["DropBoxRedirectUri"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D94JJWCtLiqoUfUhHF5mfM5mi2MIwQpaMcn1mu+DkxJTsaqS9f6bZy4+pXdMynD0DuVWzcFOJsE/6dTNzxCrIMT/fCQ8Sq2hiKMLOczpBao=")]
        public string OneDriveClientId => ((string)(this["OneDriveClientId"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rp2YO1i8XYXs24egYC3SoMIr3YRw7v5vQ5eRCm1LTjnllLJg4GnZBvwBVCvVBI/feGsdX2PFE0uhZPVfcIsUW0ru8pyIMbXiqpoICsQrkP/Nqg4ITC+EXqtU2beIuuPZ")]
        public string OneDriveRedirectUri => ((string)(this["OneDriveRedirectUri"]));
    }
}
