  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clipboard.Properties 
{
    internal partial class Settings 
    {

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UHoVxZGT/Jpf2IuRU7e+PWZ6iO2nDTQO")]
        public string DropBoxAppKey => ((string)(this["DropBoxAppKey"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G4kxoxHKXy3fdV5IcSoVrdUqd9MSg5OaEdFr3ylfRCPnQ7C+oL6qmA==")]
        public string DropBoxRedirectUri => ((string)(this["DropBoxRedirectUri"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yqa7ol269Lihdc8Mf0Bi0LIcfssrGejnBy3M29LlPYdtKUGIBmneQRB6l9XZ6dIX1lP6aVrVybdzJk4PmeIXHkw/1Ukphe2X2aTNHSG8/AE=")]
        public string OneDriveClientId => ((string)(this["OneDriveClientId"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G4kxoxHKXy3fdV5IcSoVrfDtdvB1H5qP79IxfweUkB0tQv/gFdifCnzF7QsrdzUvWlWIwPcabbxjDpCBdYmdjUfSf0tEQIk0COh4BS9Vv9UZ55AA389WD93kjy5z2vXJ")]
        public string OneDriveRedirectUri => ((string)(this["OneDriveRedirectUri"]));
    }
}
