  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clipboard.Properties 
{
    internal partial class Settings 
    {

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2UsbpwKkm+dFn7A/Mply2hOGBm+mPuem")]
        public string DropBoxAppKey => ((string)(this["DropBoxAppKey"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61/ouZZkrrVlZMqyoSdleZocwekBTpRY4Ju12l/R7nPa84uPAxpB6A==")]
        public string DropBoxRedirectUri => ((string)(this["DropBoxRedirectUri"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MMG7M0wIl6OpoTpK0N9QXJuVL0WM42sgd2Ap2R/L8XNTqSqYP2sZrNDH0+z63bMalvZq3MoK9kW/YeMZJuzmDlY1s2dw9xQE3WBbssxwwmg=")]
        public string OneDriveClientId => ((string)(this["OneDriveClientId"]));

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61/ouZZkrrVlZMqyoSdleaGnuPeC0guGm1e4TRLeJ2f6mmdwgCywTVSAuT4rh0MA1brw/9ihvxMzz3+bu7qWGiYodnF/fsHq37nIMSnD8j65r+bVWepeMChDfUrhP+jX")]
        public string OneDriveRedirectUri => ((string)(this["OneDriveRedirectUri"]));
    }
}
